name: ecomme_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.2
  supabase_auth_ui: ^0.5.4
  google_sign_in: ^6.2.2
  google_nav_bar: ^5.0.7
  provider: ^6.1.2  #this is provider we use for save data 
  shared_preferences: ^2.3.5
  share_plus: ^10.1.4
  internet_connection_checker: ^3.0.1
  palette_generator: ^0.3.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/vidios/


